#!/usr/bin/env bash
# One-command deploy of RepoPilot onto free tiers.
#
#   API + arq worker + Redis -> Hugging Face Docker Space (2 vCPU / 16 GB free)
#   Postgres + pgvector      -> whatever DSN you put in .env.deploy (Neon, Supabase)
#   Next.js web              -> Vercel
#
# Usage:
#   cp infra/deploy/.env.deploy.example .env.deploy   # then fill it in
#   ./infra/deploy/deploy.sh                          # db + api + web
#   ./infra/deploy/deploy.sh api web                  # only those stages
#
# Needs: git, curl, psql, uv, npx (Vercel CLI is fetched via npx).
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"
ENV_FILE="${ENV_FILE:-.env.deploy}"

die() { echo "deploy: $*" >&2; exit 1; }
step() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }

[ -f "$ENV_FILE" ] || die "$ENV_FILE not found — copy infra/deploy/.env.deploy.example"
set -a; . "./$ENV_FILE"; set +a

for v in HF_TOKEN HF_SPACE POSTGRES_DSN REPOPILOT_SESSION_SECRET WEB_URL; do
  [ -n "${!v:-}" ] || die "$v is unset in $ENV_FILE"
done
[ -n "${GROQ_API_KEY:-}${CEREBRAS_API_KEY:-}${HUGGINGFACE_API_KEY:-}" ] \
  || die "set at least one of GROQ_API_KEY / CEREBRAS_API_KEY / HUGGINGFACE_API_KEY"

SPACE_URL="https://${HF_SPACE/\//-}.hf.space"
SPACE_URL="$(echo "$SPACE_URL" | tr '[:upper:]' '[:lower:]')"
stages=("$@"); [ ${#stages[@]} -eq 0 ] && stages=(db api web)
has() { printf '%s\n' "${stages[@]}" | grep -qx "$1"; }

# ── db ──────────────────────────────────────────────────────────────────────
# psql needs a libpq URL; the app's DSN carries SQLAlchemy's +psycopg driver tag.
if has db; then
  step "Postgres: extensions + alembic upgrade head"
  psql "${POSTGRES_DSN/+psycopg/}" -v ON_ERROR_STOP=1 -f infra/postgres/init.sql
  (cd packages/ingestion && POSTGRES_DSN="$POSTGRES_DSN" uv run alembic upgrade head)
fi

# ── api ─────────────────────────────────────────────────────────────────────
if has api; then
  step "Hugging Face Space: secrets"
  hf_secret() {
    [ -n "${2:-}" ] || return 0
    curl -fsS -X POST "https://huggingface.co/api/spaces/$HF_SPACE/secrets" \
      -H "Authorization: Bearer $HF_TOKEN" -H "Content-Type: application/json" \
      -d "$(printf '{"key":"%s","value":%s}' "$1" "$(printf '%s' "$2" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')")" \
      >/dev/null || die "could not set secret $1 (does the Space $HF_SPACE exist?)"
    echo "  set $1"
  }
  hf_secret POSTGRES_DSN "$POSTGRES_DSN"
  hf_secret REPOPILOT_SESSION_SECRET "$REPOPILOT_SESSION_SECRET"
  hf_secret GROQ_API_KEY "${GROQ_API_KEY:-}"
  hf_secret CEREBRAS_API_KEY "${CEREBRAS_API_KEY:-}"
  hf_secret HUGGINGFACE_API_KEY "${HUGGINGFACE_API_KEY:-}"
  hf_secret GITHUB_PAT "${GITHUB_PAT:-}"
  hf_secret REPOPILOT_ENV production
  hf_secret REPOPILOT_LOG_LEVEL "${REPOPILOT_LOG_LEVEL:-INFO}"
  hf_secret REPOPILOT_SESSION_COOKIE_SECURE true
  hf_secret REPOPILOT_WEB_ORIGINS "$WEB_URL"

  step "Hugging Face Space: push build context"
  # The Space repo is generated, never committed: HF requires the Dockerfile at
  # the repo root, and this one belongs under infra/deploy/. Built from
  # `git archive HEAD`, so uncommitted work is deliberately not deployed.
  work="$(mktemp -d)"; trap 'rm -rf "$work"' EXIT
  git archive HEAD | tar -x -C "$work"
  cp infra/deploy/Dockerfile.space "$work/Dockerfile"
  cat > "$work/README.md" <<EOF
---
title: RepoPilot API
emoji: 🧭
colorFrom: indigo
colorTo: blue
sdk: docker
app_port: 7860
pinned: false
---

Backend for RepoPilot. Generated by infra/deploy/deploy.sh — do not edit here.
EOF
  git -C "$work" init -q -b main
  git -C "$work" add -A
  git -C "$work" -c user.email=deploy@repopilot -c user.name=deploy \
    commit -qm "deploy $(git rev-parse --short HEAD)"
  git -C "$work" push -q --force \
    "https://user:$HF_TOKEN@huggingface.co/spaces/$HF_SPACE" main
  echo "  pushed. Build logs: https://huggingface.co/spaces/$HF_SPACE?logs=build"
fi

# ── web ─────────────────────────────────────────────────────────────────────
if has web; then
  step "Vercel: env + production deploy"
  vercel() { npx --yes vercel@latest "$@" --cwd apps/web --token "$VERCEL_TOKEN" --yes; }
  [ -n "${VERCEL_TOKEN:-}" ] || die "VERCEL_TOKEN is unset in $ENV_FILE"
  vercel link --project "${VERCEL_PROJECT:-repopilot}" >/dev/null

  set_env() {
    [ -n "${2:-}" ] || return 0
    vercel env rm "$1" production >/dev/null 2>&1 || true
    printf '%s' "$2" | vercel env add "$1" production >/dev/null
    echo "  set $1"
  }
  set_env API_PROXY_TARGET "$SPACE_URL"
  set_env NEXT_PUBLIC_API_BASE_URL "${NEXT_PUBLIC_API_BASE_URL:-}"
  set_env AUTH_SECRET "${AUTH_SECRET:?set AUTH_SECRET in $ENV_FILE}"
  set_env NEXTAUTH_URL "$WEB_URL"
  set_env AUTH_GITHUB_ID "${AUTH_GITHUB_ID:-}"
  set_env AUTH_GITHUB_SECRET "${AUTH_GITHUB_SECRET:-}"
  set_env AUTH_GOOGLE_ID "${AUTH_GOOGLE_ID:-}"
  set_env AUTH_GOOGLE_SECRET "${AUTH_GOOGLE_SECRET:-}"
  set_env REPOPILOT_SESSION_SECRET "$REPOPILOT_SESSION_SECRET"
  set_env REPOPILOT_SESSION_COOKIE_SECURE true

  vercel deploy --prod
fi

step "Done"
echo "  API: $SPACE_URL/health"
echo "  Web: $WEB_URL"
echo "  First request after a cold Space wakes it — allow ~60s."
